Run webpack rake task for v0.27
decidim/decidim-maintainers_toolbox pull request #7
Opened 2024-07-16 07:49 UTC by andreslucena

Until now, the `decidim-releaser` script only was working for Patch versions (i.e. from v0.28.0 to v0.28.1). 

This PR introduces the feature to make Release Candidates using this same tool (i.e. from v0.29.0.dev to v0.29.0.rc1).

For doing that, what I've done is:

1. Extract the Patch code to its own class (`ReleasePatchVersion`)
2. Make a `ReleaseCandidateVersion` class
3. Move the common logic to the `ReleaserUtils` module 

After this is merged, the next iteration would be to have a new class from `ReleaseMinorVersion` (from v0.29.0.rcX to v0.29.0)

2024-07-19 07:54 UTC, alecslupu requested changes
One small change, and i think is good to go.

2024-07-19 07:54 UTC, alecslupu commented on lib/decidim/maintainers_toolbox/release_candidate_version.rb
> +### 1.1. Update your Gemfile
Since we have the policy of one Decidim version, has one ruby version, i would add here also the `Upgrade ruby step`

2025-02-12 10:35 UTC, andreslucena commented on lib/decidim/maintainers_toolbox/release_candidate_version.rb
> +### 1.1. Update your Gemfile
Done at  f45ddcc

2025-02-12 10:58 UTC, andreslucena commented
@alecslupu this is ready for another round (I forget about this PR and it'd be nice to have it for the v0.30 release :D)

2025-02-13 00:39 UTC, alecslupu approved these changes
:+1: 
LGTM . let's see how it behaves ..

2025-02-18 13:39 UTC, andreslucena commented
@alecslupu this is ready for another round! 

I try it out with 14096 and 14109, and apart from some missing requires (like using the `present?` method from ActiveSupport without doing the require in the file that was necessary) I also found another bug related to the tests: we were doing the tests execution once the release branch was prepared and we should do it at the begging of the process, so it's much easier to restart and try again. This is fixed too. 

About the documentation, the instructions are available at #14066, so we can merge that after this is merged.

2025-03-03 09:01 UTC, alecslupu approved these changes
I haven't managed to test it, but reading through it, LGTM

2025-03-03 09:01 UTC, merged